// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID
	Name           string
	Age            int32
	PhoneNumber    string
	Email          string
	PasswordHash   string
	TokenVersion   sql.NullInt32
	AccessLevel    sql.NullString
	VerifiedStatus sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	LastLoggedIn   sql.NullTime
}
